---
os: [linux]

before_install:
  - chmod +x ${TRAVIS_BUILD_DIR}/.travis.d/*${TRAVIS_OS_NAME}.sh

install:
  - ${TRAVIS_BUILD_DIR}/.travis.d/install_${TRAVIS_OS_NAME}.sh

script:
  - packer build ${TRAVIS_BUILD_DIR}/tooler.build.${TRAVIS_OS_NAME}.pkr.hcl